# Generated by Django 2.1.7 on 2019-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_update_password_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
